# Generated by Django 6.0.7 on 2026-07-15 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=300)),
                ('youtube_url', models.URLField()),
                ('video_id', models.CharField(max_length=30)),
                ('thumbnail_url', models.URLField()),
                ('Summary', models.TextField()),
                ('Summary_language', models.CharField(default='english', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summarizer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
