# Generated by Django 6.0.7 on 2026-07-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='channel_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='summary',
            name='duration',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='summary',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
