# Generated by Django 6.0.7 on 2026-07-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerier', '0002_summary_channel_name_summary_duration_summary_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='compound_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='negetive_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='neutral_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='positive_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='sentimet',
            field=models.CharField(default='newtral', max_length=20),
        ),
    ]
