# Generated by Django 6.0.7 on 2026-07-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerier', '0003_summary_compound_score_summary_negetive_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='sentimet',
        ),
        migrations.AddField(
            model_name='summary',
            name='sentiment',
            field=models.CharField(default='Neutral', max_length=20),
        ),
    ]
