# Generated by Django 6.0.7 on 2026-07-27 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summerier', '0004_remove_summary_sentimet_summary_sentiment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='negetive_score',
            new_name='negative_score',
        ),
    ]
